### ISSUE TITLE
32- and 64-bit 

### ISSUE THREAD

**Issue by r3sus** [CleanFlash/installer#11]
Hello and thanks a lot for your work!

Why does versions with 32 in name are installed in 64 folder and vice versa?

**Comment by darktohka** [comment]
Hey!

It's a bit confusing, but because of backwards compatibility reasons, Windows's 64-bit system folder is called System32.

This is because earlier versions of Windows were 32-bit only and thus they were named System32.

But this changed when 64-bit support was introduced. Instead of worrying about potential issues, Microsoft decided to rename the previous System32 folder to SysWOW64 (which is actually the 32-bit system folder now, despite being called SysWOW64!), and now the System32 folder holds 64-bit system files.

Hope that made sense.

**Comment by darktohka** [comment]
More info: https://www.howtogeek.com/326509/whats-the-difference-between-the-system32-and-syswow64-folders-in-windows/

**Comment by r3sus** [comment]
Got it, thanks for the lightning fast answer and your support!
